#!/usr/bin/env node
/* migrate.mjs — convert a markdown CRM vault (Obsidian-style) into data.js.
 *
 *   node migrate.mjs [vaultDir] [outDir]
 *
 * Defaults: vaultDir = three levels up from this script (repo root),
 *           outDir   = ../example  (the bundled example vault).
 *
 * It parses YAML frontmatter + "## Section" bodies, rewrites [[wikilinks]] and
 * relationship fields to slugs, and drops auto/Dataview sections (those are
 * computed at render time). Output is a single window.CRM assignment. */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const VAULT = resolve(process.argv[2] || join(here, "..", "..", ".."));
const OUT = resolve(process.argv[3] || join(here, "..", "example"));

const DIRS = { contacts: "contact", companies: "company", deals: "deal", interactions: "interaction", tasks: "task" };
const COMPUTED = new Set(["Interaction History", "Linked Deals", "Key Contacts", "Active Deals"]);
// relationship fields whose values are [[wikilinks]] -> store as slugs
const LINK_FIELDS = new Set(["company", "primary_contact", "deal"]);
const LIST_LINK_FIELDS = new Set(["participants", "related_to"]);

function slug(name) {
  return String(name).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
function stripLink(v) {
  const m = String(v).match(/^\[\[([^\]|]+)(?:\|[^\]]+)?\]\]$/);
  return m ? m[1].trim() : v;
}
function coerce(v) {
  if (typeof v !== "string") return v;
  v = v.trim();
  if (/^-?\d+$/.test(v)) return parseInt(v, 10);
  return v;
}
function unquote(v) {
  v = v.trim();
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) return v.slice(1, -1);
  return v;
}

// minimal YAML for this known schema: scalars, inline [a, b] arrays, block "- x" lists
function parseFrontmatter(text) {
  const fm = {};
  const lines = text.split("\n");
  let key = null;
  for (const raw of lines) {
    const line = raw.replace(/\s+$/, "");
    if (line === "") continue;
    const block = line.match(/^\s+-\s+(.*)$/);
    if (block && key) { (fm[key] = Array.isArray(fm[key]) ? fm[key] : []).push(stripLink(unquote(block[1]))); continue; }
    const kv = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (!kv) continue;
    key = kv[1];
    let val = kv[2];
    if (val === "") { fm[key] = []; continue; }        // block list follows (or empty)
    if (val.startsWith("[") && val.endsWith("]")) {     // inline array
      fm[key] = val.slice(1, -1).split(",").map((s) => unquote(s.trim())).filter(Boolean);
      key = null; continue;
    }
    fm[key] = coerce(stripLink(unquote(val)));
    key = null;
  }
  return fm;
}

function parseSections(body) {
  const sections = {};
  let cur = null, buf = [];
  const flush = () => { if (cur) sections[cur] = buf.join("\n").trim(); };
  for (const line of body.split("\n")) {
    const h = line.match(/^##\s+(.*)$/);
    if (h) { flush(); cur = h[1].trim(); buf = []; continue; }
    if (line.match(/^#\s+/)) continue; // skip H1 title
    if (cur) buf.push(line);
  }
  flush();
  for (const k of Object.keys(sections)) if (COMPUTED.has(k) || sections[k] === "") delete sections[k];
  return sections;
}

function readEntities(type) {
  const dir = join(VAULT, type);
  if (!existsSync(dir)) return {};
  const out = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".md"))) {
    const text = readFileSync(join(dir, file), "utf8");
    const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
    if (!m) continue;
    const fm = parseFrontmatter(m[1]);
    const sections = parseSections(m[2]);
    const base = file.replace(/\.md$/, "");
    const name = fm.name || fm.title || base;
    const id = slug(base);
    const e = { type: DIRS[type], id, name, sections };
    for (const [k, v] of Object.entries(fm)) {
      if (k === "entity") continue;
      if (LINK_FIELDS.has(k)) e[k] = v ? slug(v) : "";
      else if (LIST_LINK_FIELDS.has(k)) e[k] = (v || []).map((x) => (k === "participants" ? slug(x) : x));
      else e[k] = v;
    }
    out[id] = e;
  }
  return out;
}

const CRM = { meta: { business: process.env.BUSINESS || "", tagline: process.env.TAGLINE || "", accent: process.env.ACCENT || "" } };
let total = 0;
for (const type of Object.keys(DIRS)) {
  CRM[type] = readEntities(type);
  const n = Object.keys(CRM[type]).length;
  total += n;
  console.log(`  ${type.padEnd(13)} ${n}`);
}

const banner = "/* AUTO-GENERATED by scripts/migrate.mjs — but safe to hand-edit.\n" +
  " * This file IS the database. The crm-operator skill edits it directly. */\n";
writeFileSync(join(OUT, "data.js"), banner + "window.CRM = " + JSON.stringify(CRM, null, 2) + ";\n");
console.log(`\n  ${total} entities -> ${join(OUT, "data.js")}`);
