/* AUTO-GENERATED by scripts/migrate.mjs — but safe to hand-edit.
 * This file IS the database. The crm-operator skill edits it directly. */
window.CRM = {
  "contacts": {
    "aisha-mohammed": {
      "type": "contact",
      "id": "aisha-mohammed",
      "name": "Aisha Mohammed",
      "sections": {
        "Background": "VP Engineering at Steelforge Manufacturing. Leading their Industry 4.0 initiative — connecting factory floor equipment to a centralized monitoring system. 20 years in manufacturing IT. Reports to the CIO.",
        "Relationship History": "Met at Industrial IoT World conference in March 2026. She was attending sessions on predictive maintenance and stopped by our booth. Had a 30-minute conversation about their challenges. Exchanged contacts and scheduled a follow-up requirements gathering session.",
        "Key Interests & Pain Points": "- Factory floor has 500+ pieces of equipment across 15 plants, mostly unconnected\n- Needs real-time dashboards for plant managers showing equipment health\n- Predictive maintenance is the long-term goal — reduce unplanned downtime by 30%\n- Integration with their SAP ERP system is a hard requirement",
        "Notes": "- Very senior and influential, but not the final budget holder (CIO is)\n- Pragmatic — wants to start with a single plant pilot\n- She's building the internal business case — needs ROI projections from us"
      },
      "email": "a.mohammed@steelforgemfg.com",
      "phone": "+1-313-555-0156",
      "company": "steelforge-manufacturing",
      "role": "VP Engineering",
      "linkedin": "linkedin.com/in/aishamohammed",
      "status": "active",
      "lead_source": "Conference - Industrial IoT World 2026",
      "last_contacted": "2026-03-25",
      "tags": [
        "technical",
        "early-stage"
      ],
      "created": "2026-03-20",
      "updated": "2026-03-25"
    },
    "david-kim": {
      "type": "contact",
      "id": "david-kim",
      "name": "David Kim",
      "sections": {
        "Background": "Head of Partnerships at Quantum Labs. Handles all vendor relationships, contract negotiations, and integration partnerships. MBA from Wharton. Previously at Stripe in business development.",
        "Relationship History": "Joined the second call with [[Priya Patel]]. Handles the commercial side — pricing, contract terms, SLAs. Professional and straightforward.",
        "Key Interests & Pain Points": "- Needs clear SLAs for uptime and latency\n- Wants usage-based pricing with volume discounts\n- Looking for a partnership model, not just a vendor relationship\n- Interested in co-marketing opportunities",
        "Notes": "- Very detail-oriented on contracts — expect redlines\n- Good rapport, easy to work with\n- Handles budget approval (Priya handles technical approval)"
      },
      "email": "d.kim@quantumlabs.io",
      "phone": "+1-415-555-0301",
      "company": "quantum-labs",
      "role": "Head of Partnerships",
      "linkedin": "linkedin.com/in/davidkim",
      "status": "active",
      "lead_source": "Referral - Priya Patel",
      "last_contacted": "2026-04-03",
      "tags": [
        "commercial",
        "partnerships"
      ],
      "created": "2026-03-18",
      "updated": "2026-04-03"
    },
    "elena-rodriguez": {
      "type": "contact",
      "id": "elena-rodriguez",
      "name": "Elena Rodriguez",
      "sections": {
        "Background": "Head of Technology at Brightpath Education. 12 years in edtech. Manages all technology decisions for 200+ school districts. Reports to the Executive Director. Previously at Khan Academy.",
        "Relationship History": "Came inbound — requested a demo through our website after seeing a webinar we hosted on LMS modernization. Enthusiastic about our platform but constrained by nonprofit procurement processes.",
        "Key Interests & Pain Points": "- Current LMS is outdated — teachers are frustrated with the UX\n- Needs offline support for rural districts with poor internet\n- Budget is grant-funded — needs to justify ROI clearly for board approval\n- Timeline pressure: wants to pilot before fall semester 2026",
        "Notes": "- Very passionate about the mission — education equity is her driving force\n- Brings [[James O'Brien]] (IT Director) to all technical discussions\n- Comfortable with Zoom calls, prefers mornings CT"
      },
      "email": "elena.r@brightpathedu.org",
      "phone": "+1-512-555-0189",
      "company": "brightpath-education",
      "role": "Head of Technology",
      "linkedin": "linkedin.com/in/elenarodriguez",
      "status": "active",
      "lead_source": "Inbound - Website demo request",
      "last_contacted": "2026-04-05",
      "tags": [
        "decision-maker",
        "education"
      ],
      "created": "2026-03-15",
      "updated": "2026-04-05"
    },
    "james-o-brien": {
      "type": "contact",
      "id": "james-o-brien",
      "name": "James O'Brien",
      "sections": {
        "Background": "IT Director at Brightpath Education. Manages infrastructure for 200+ school districts — servers, networks, devices. Will lead the technical rollout if the deal closes. 8 years at Brightpath.",
        "Relationship History": "Joined the demo session with [[Elena Rodriguez]]. Asked detailed questions about deployment models, data migration, and SSO integration. Thorough and methodical.",
        "Key Interests & Pain Points": "- Needs SSO integration with Google Workspace and Microsoft 365\n- Concerned about data migration from their current LMS (custom-built)\n- Wants on-premise deployment option for districts with data residency requirements\n- Limited team (3 IT staff) — needs turnkey solution with minimal maintenance",
        "Notes": "- Very cautious — wants to see proof of concept before recommending to the board\n- Good technical depth, asks the right questions\n- Prefers detailed documentation over demo calls"
      },
      "email": "j.obrien@brightpathedu.org",
      "phone": "+1-512-555-0224",
      "company": "brightpath-education",
      "role": "IT Director",
      "linkedin": "linkedin.com/in/jamesobrien",
      "status": "active",
      "lead_source": "Referral - Elena Rodriguez",
      "last_contacted": "2026-04-05",
      "tags": [
        "technical",
        "implementation-lead"
      ],
      "created": "2026-03-22",
      "updated": "2026-04-05"
    },
    "lisa-tran": {
      "type": "contact",
      "id": "lisa-tran",
      "name": "Lisa Tran",
      "sections": {
        "Background": "CTO of NovaPay, a fintech startup building payment infrastructure for e-commerce platforms. Leads all technical decisions. Company is Series A ($12M raised), 30 employees.",
        "Relationship History": "Introduced by [[Tom Nakamura]] from [[Coastal Ventures]]. First call on April 7, 2026 — she was direct and moving fast. Wants a demo next week and a solution in place by June.",
        "Key Interests & Pain Points": "- Current homegrown analytics can't scale past 1M events/day\n- Needs real-time event processing (sub-200ms latency)\n- White-labeled merchant-facing analytics dashboard\n- PCI DSS compliance is non-negotiable\n- Budget approved for Q2 — timeline is aggressive",
        "Notes": "- Prefers Tuesday or Wednesday for meetings\n- Fast decision-maker — wants to fast-track evaluation\n- TODO: get email and phone number"
      },
      "email": "",
      "phone": "",
      "company": "novapay",
      "role": "CTO",
      "linkedin": "",
      "status": "active",
      "lead_source": "Referral - Tom Nakamura (Coastal Ventures)",
      "last_contacted": "2026-04-07",
      "tags": [
        "decision-maker",
        "technical",
        "founder"
      ],
      "created": "2026-04-07",
      "updated": "2026-04-07"
    },
    "marcus-johnson": {
      "type": "contact",
      "id": "marcus-johnson",
      "name": "Marcus Johnson",
      "sections": {
        "Background": "VP Engineering at Meridian Health, reporting to [[Sarah Chen]]. Manages a team of 40 engineers. Will be the implementation lead if the deal closes. 10 years at Meridian, deep knowledge of their legacy systems.",
        "Relationship History": "Introduced by Sarah Chen during the discovery call. Very hands-on — asked most of the technical questions during the call. Followed up via email with a detailed requirements doc.",
        "Key Interests & Pain Points": "- Needs clear migration path from Oracle Health with minimal data loss\n- Concerned about his team's capacity — wants professional services support\n- Interested in our API documentation quality and developer experience\n- Wants a sandbox environment for his team to evaluate before committing",
        "Notes": "- Very responsive on email — typically replies within 2 hours\n- Ex-AWS engineer — speaks fluently about cloud infrastructure\n- Will be the day-to-day contact during implementation"
      },
      "email": "m.johnson@meridianhealth.com",
      "phone": "+1-617-555-0198",
      "company": "meridian-health",
      "role": "VP Engineering",
      "linkedin": "linkedin.com/in/marcusjohnson",
      "status": "active",
      "lead_source": "Referral - Sarah Chen",
      "last_contacted": "2026-04-01",
      "tags": [
        "technical",
        "implementation-lead"
      ],
      "created": "2026-03-15",
      "updated": "2026-04-01"
    },
    "mike-torres": {
      "type": "contact",
      "id": "mike-torres",
      "name": "Mike Torres",
      "sections": {
        "Background": "VP Product at RouteAI, a logistics startup building route optimization software. Owns the product roadmap and is leading the initiative to add analytics to their platform. Directly responsible for vendor selection on this project.",
        "Relationship History": "Introduced through [[Tom Nakamura]] at [[Coastal Ventures]]. First call on April 7, 2026 — demo went well, he was impressed with our real-time streaming dashboard and white-label customization. Said it's \"exactly what our customers have been asking for.\"",
        "Key Interests & Pain Points": "- Customers demanding delivery performance analytics (on-time %, cost per delivery, efficiency)\n- Current approach is manual SQL queries — doesn't scale, not customer-facing\n- Needs embeddable, white-labeled, multi-tenant dashboard\n- Wants usage-based pricing tied to delivery volume\n- Timeline pressure: pilot in May, full rollout Q3",
        "Notes": "- Product-focused thinker — cares about UX and customer experience\n- Needs CTO ([[Raj Mehta]]) buy-in for technical architecture\n- TODO: get email and phone number"
      },
      "email": "",
      "phone": "",
      "company": "routeai",
      "role": "VP Product",
      "linkedin": "",
      "status": "active",
      "lead_source": "Referral - Tom Nakamura (Coastal Ventures)",
      "last_contacted": "2026-04-07",
      "tags": [
        "product",
        "champion"
      ],
      "created": "2026-04-07",
      "updated": "2026-04-07"
    },
    "priya-patel": {
      "type": "contact",
      "id": "priya-patel",
      "name": "Priya Patel",
      "sections": {
        "Background": "Co-founder and CTO of Quantum Labs. PhD in distributed systems from Stanford. Built the core code review platform. Makes all technical and vendor decisions. Fast decision-maker — doesn't like long sales processes.",
        "Relationship History": "Introduced by [[Tom Nakamura]] from [[Coastal Ventures]] (their seed investor). Had an initial call where she explained their analytics integration needs. Very direct and efficient communicator.",
        "Key Interests & Pain Points": "- Needs to ship analytics features to enterprise customers by Q3 2026\n- Wants a self-serve API with usage-based pricing — no enterprise sales process\n- Concerned about latency — their platform needs sub-100ms API responses\n- Evaluating build vs. buy — our API needs to be compelling enough vs. building in-house",
        "Notes": "- Prefers Slack or short calls over email\n- Makes decisions quickly — if we pass the technical review, deal could close in weeks\n- Very well-connected in SF dev tools scene"
      },
      "email": "priya@quantumlabs.io",
      "phone": "+1-415-555-0267",
      "company": "quantum-labs",
      "role": "CTO & Co-founder",
      "linkedin": "linkedin.com/in/priyapatel",
      "status": "active",
      "lead_source": "Referral - Tom Nakamura (Coastal Ventures)",
      "last_contacted": "2026-04-03",
      "tags": [
        "decision-maker",
        "technical",
        "founder"
      ],
      "created": "2026-03-12",
      "updated": "2026-04-03"
    },
    "raj-mehta": {
      "type": "contact",
      "id": "raj-mehta",
      "name": "Raj Mehta",
      "sections": {
        "Background": "CTO at RouteAI. Needs to sign off on the technical architecture before the deal can progress. Haven't spoken with him yet — technical review scheduled for next week.",
        "Relationship History": "Mentioned by [[Mike Torres]] during the demo call. Not yet met directly.",
        "Key Interests & Pain Points": "- Will care about: multi-tenant data isolation, API design, latency, security\n- Needs to approve the integration architecture before Mike can proceed",
        "Notes": "- TODO: get contact details from Mike Torres\n- TODO: schedule technical review call for next week"
      },
      "email": "",
      "phone": "",
      "company": "routeai",
      "role": "CTO",
      "linkedin": "",
      "status": "prospect",
      "lead_source": "Referral - Mike Torres",
      "last_contacted": [],
      "tags": [
        "decision-maker",
        "technical",
        "TODO"
      ],
      "created": "2026-04-07",
      "updated": "2026-04-07"
    },
    "sarah-chen": {
      "type": "contact",
      "id": "sarah-chen",
      "name": "Sarah Chen",
      "sections": {
        "Background": "CTO at Meridian Health, reporting directly to the CEO. 15+ years in health IT. Previously VP Engineering at Epic Systems. Drives all technology vendor decisions for the network. Strong opinions on cloud architecture and data security.",
        "Relationship History": "Met at HealthTech Summit in March 2026. Had a 20-minute conversation at the networking dinner — she was frustrated with their current Oracle Health setup and interested in our platform migration capabilities. Exchanged cards, scheduled a discovery call the following week.",
        "Key Interests & Pain Points": "- Needs to modernize patient data infrastructure before Oracle contract expires Q3 2026\n- Concerned about HIPAA compliance in cloud migration\n- Wants a phased rollout approach — can't afford downtime across 12 hospitals\n- Interested in AI-powered patient flow optimization (future phase)",
        "Notes": "- Prefers email over phone calls\n- Very detail-oriented — comes to meetings with a prepared list of questions\n- Has a good relationship with [[Marcus Johnson]] (her direct report who handles implementation)"
      },
      "email": "s.chen@meridianhealth.com",
      "phone": "+1-617-555-0142",
      "company": "meridian-health",
      "role": "CTO",
      "linkedin": "linkedin.com/in/sarahchen",
      "status": "active",
      "lead_source": "Conference - HealthTech Summit 2026",
      "last_contacted": "2026-04-07",
      "tags": [
        "decision-maker",
        "technical"
      ],
      "created": "2026-03-10",
      "updated": "2026-04-07"
    },
    "tom-nakamura": {
      "type": "contact",
      "id": "tom-nakamura",
      "name": "Tom Nakamura",
      "sections": {
        "Background": "Managing Partner at Coastal Ventures, a seed-stage VC firm. Led our seed round. 15 years in venture capital, previously at Andreessen Horowitz. Focus on B2B SaaS and developer tools. Active board observer.",
        "Relationship History": "Our seed investor — relationship goes back to early 2026. Very supportive, makes warm introductions to his portfolio companies and network. Introduced us to [[Priya Patel]] at [[Quantum Labs]], [[Lisa Tran]] at [[NovaPay]], and [[Mike Torres]] at [[RouteAI]].",
        "Key Interests & Pain Points": "- Wants to see us grow ARR for Series A readiness\n- Interested in our product-led growth metrics\n- Wants us to present at their annual LP meeting in June\n- Looking for co-investment opportunities for our Series A",
        "Notes": "- Very well-connected — each introduction he makes is high quality\n- Prefers monthly check-in calls (first Monday of the month)\n- Also an advisor on go-to-market strategy"
      },
      "email": "tom@coastalvc.com",
      "phone": "+1-305-555-0178",
      "company": "coastal-ventures",
      "role": "Managing Partner",
      "linkedin": "linkedin.com/in/tomnakamura",
      "status": "active",
      "lead_source": "Investor",
      "last_contacted": "2026-03-28",
      "tags": [
        "investor",
        "referral-source",
        "partner"
      ],
      "created": "2026-02-15",
      "updated": "2026-04-07"
    }
  },
  "companies": {
    "brightpath-education": {
      "type": "company",
      "id": "brightpath-education",
      "name": "Brightpath Education",
      "sections": {
        "Overview": "Brightpath is a K-12 education technology nonprofit that provides learning management systems to school districts across Texas and the Southwest. They serve 200+ school districts and are looking to upgrade their LMS infrastructure. Funded through a mix of grants and district contracts.",
        "Notes": "- Procurement is slow — requires board approval for contracts over $100K\n- Strong existing relationship with their Head of Technology\n- They're also evaluating Canvas and Schoology"
      },
      "domain": "brightpathedu.org",
      "industry": "Education",
      "size": "mid-market",
      "status": "prospect",
      "location": "Austin, TX",
      "arr_potential": 150000,
      "tags": [
        "education",
        "lms",
        "mid-market"
      ],
      "created": "2026-03-15",
      "updated": "2026-04-05"
    },
    "coastal-ventures": {
      "type": "company",
      "id": "coastal-ventures",
      "name": "Coastal Ventures",
      "sections": {
        "Overview": "Coastal Ventures is a seed-stage VC firm focused on B2B SaaS. They invested in our seed round and are an active partner — referring portfolio companies our way and providing market intelligence. Managing partner Tom Nakamura is our primary relationship.",
        "Notes": "- Good source of warm introductions to their portfolio companies\n- They introduced us to Quantum Labs\n- Annual LP meeting in June — they may want us to present"
      },
      "domain": "coastalvc.com",
      "industry": "Venture Capital",
      "size": "smb",
      "status": "partner",
      "location": "Miami, FL",
      "arr_potential": 50000,
      "tags": [
        "vc",
        "partner",
        "referral-source"
      ],
      "created": "2026-02-15",
      "updated": "2026-03-28"
    },
    "meridian-health": {
      "type": "company",
      "id": "meridian-health",
      "name": "Meridian Health",
      "sections": {
        "Overview": "Meridian Health is a regional healthcare network with 12 hospitals and 200+ clinics across the Northeast. They're modernizing their patient management infrastructure and looking to migrate from a legacy on-premise system to a cloud-based platform. Annual IT budget is ~$15M. Key decision-making is centralized through their CTO office.",
        "Notes": "- Fiscal year ends in June — budget decisions typically finalized by April\n- Strong compliance requirements (HIPAA) — security review will be thorough\n- Current vendor is Oracle Health (formerly Cerner) — contract expires Q3 2026"
      },
      "domain": "meridianhealth.com",
      "industry": "Healthcare",
      "size": "enterprise",
      "status": "prospect",
      "location": "Boston, MA",
      "arr_potential": 240000,
      "tags": [
        "healthcare",
        "enterprise-sales"
      ],
      "created": "2026-03-10",
      "updated": "2026-04-01"
    },
    "novapay": {
      "type": "company",
      "id": "novapay",
      "name": "NovaPay",
      "sections": {
        "Overview": "NovaPay is a fintech startup building payment infrastructure for e-commerce platforms. Series A ($12M raised), 30 employees, based in New York. They serve ~500 e-commerce merchants. Introduced by [[Tom Nakamura]] at [[Coastal Ventures]] (portfolio company).\n\nThey need real-time transaction analytics for their merchant dashboard. Currently using a homegrown solution that can't scale past 1M events/day. Budget approved for Q2, need a solution by June.",
        "Notes": "- Coastal Ventures portfolio company — warm intro from Tom\n- Fast-moving evaluation — wants demo next week\n- PCI DSS compliance is a hard requirement"
      },
      "domain": "novapay.com",
      "industry": "Fintech",
      "size": "startup",
      "status": "prospect",
      "location": "New York, NY",
      "arr_potential": 0,
      "tags": [
        "fintech",
        "payments",
        "coastal-portfolio"
      ],
      "created": "2026-04-07",
      "updated": "2026-04-07"
    },
    "quantum-labs": {
      "type": "company",
      "id": "quantum-labs",
      "name": "Quantum Labs",
      "sections": {
        "Overview": "Quantum Labs builds developer productivity tools — primarily a code review platform used by ~500 engineering teams. Series B ($40M raised). They need to integrate our API into their platform to offer analytics to their customers. Fast-moving team, technical founders, short sales cycles.",
        "Notes": "- Engineering-led buying process — the CTO makes the call\n- They evaluated three competitors before reaching out to us\n- Strong preference for self-serve onboarding and usage-based pricing"
      },
      "domain": "quantumlabs.io",
      "industry": "Developer Tools",
      "size": "mid-market",
      "status": "prospect",
      "location": "San Francisco, CA",
      "arr_potential": 85000,
      "tags": [
        "devtools",
        "api",
        "mid-market"
      ],
      "created": "2026-03-12",
      "updated": "2026-04-03"
    },
    "routeai": {
      "type": "company",
      "id": "routeai",
      "name": "RouteAI",
      "sections": {
        "Overview": "RouteAI is a logistics startup building route optimization software for last-mile delivery companies. Series A ($8M raised), 25 employees, based in Chicago. They serve ~200 delivery company customers, processing 500K deliveries/day. Introduced by [[Tom Nakamura]] at [[Coastal Ventures]] (portfolio company).\n\nTheir customers are asking for delivery performance analytics — on-time rates, driver efficiency, cost-per-delivery trends. Currently handling this with manual SQL queries. They want to embed a self-serve analytics dashboard into their platform.",
        "Notes": "- Coastal Ventures portfolio company — third referral from Tom (after Quantum Labs and NovaPay)\n- Strong product-market fit signal: customers are already asking for this feature\n- Multi-tenant requirement is key — each delivery company sees only their data\n- CTO Raj Mehta needs to sign off on technical architecture"
      },
      "domain": "routeai.com",
      "industry": "Logistics",
      "size": "startup",
      "status": "prospect",
      "location": "Chicago, IL",
      "arr_potential": 80000,
      "tags": [
        "logistics",
        "analytics",
        "coastal-portfolio"
      ],
      "created": "2026-04-07",
      "updated": "2026-04-07"
    },
    "steelforge-manufacturing": {
      "type": "company",
      "id": "steelforge-manufacturing",
      "name": "Steelforge Manufacturing",
      "sections": {
        "Overview": "Steelforge is a Fortune 500 steel and automotive parts manufacturer with 15 plants across the Midwest. They're in the early stages of an Industry 4.0 initiative — connecting factory floor equipment to a centralized IoT dashboard for predictive maintenance and efficiency monitoring. Early conversations, big potential.",
        "Notes": "- Very early stage — still building internal business case\n- Multiple stakeholders involved: VP Engineering, VP Operations, CIO\n- Budget hasn't been allocated yet — likely Q1 2027\n- Long sales cycle expected (6-12 months)"
      },
      "domain": "steelforgemfg.com",
      "industry": "Manufacturing",
      "size": "enterprise",
      "status": "prospect",
      "location": "Detroit, MI",
      "arr_potential": 320000,
      "tags": [
        "manufacturing",
        "iot",
        "enterprise-sales"
      ],
      "created": "2026-03-20",
      "updated": "2026-03-25"
    }
  },
  "deals": {
    "brightpath-education-lms-rollout": {
      "type": "deal",
      "id": "brightpath-education-lms-rollout",
      "name": "LMS Rollout",
      "sections": {
        "Summary": "Brightpath wants to replace their custom-built LMS with our platform across 200+ school districts. The deal includes platform licensing ($120K/yr), data migration ($20K), and training ($10K). Nonprofit procurement — requires board approval.",
        "Requirements": "- Offline-capable for rural districts with limited internet\n- SSO integration with Google Workspace and Microsoft 365\n- Data migration from custom-built LMS (PostgreSQL backend)\n- On-premise deployment option for districts with data residency requirements\n- Accessibility compliance (WCAG 2.1 AA)\n- Teacher training program and documentation",
        "Competition": "- **Canvas (Instructure)** — strong brand in education, higher price point\n- **Schoology (PowerSchool)** — already used by some districts, switching cost is low\n- Our advantage: offline support, lower cost for nonprofits, modern UX",
        "Stage History": "- 2026-03-15: → lead (inbound demo request from Elena Rodriguez)\n- 2026-03-22: lead → qualified (demo confirmed fit, Elena aligned on requirements)",
        "Notes": "- Board meets quarterly — next meeting is May 15, need materials ready by May 1\n- Elena is our champion but James O'Brien needs to sign off on technical feasibility\n- Pilot with 5 districts before full rollout could de-risk the board decision"
      },
      "company": "brightpath-education",
      "primary_contact": "elena-rodriguez",
      "value": 150000,
      "currency": "USD",
      "stage": "qualified",
      "probability": 25,
      "expected_close": "2026-08-15",
      "owner": "Our Team",
      "tags": [
        "education",
        "lms",
        "nonprofit"
      ],
      "created": "2026-03-22",
      "updated": "2026-04-05"
    },
    "coastal-ventures-seed-investment": {
      "type": "deal",
      "id": "coastal-ventures-seed-investment",
      "name": "Seed Investment",
      "sections": {
        "Summary": "Seed investment from Coastal Ventures. $50K as part of our $500K seed round. Tom Nakamura is our primary relationship — board observer, advisor, and active referral source. This is a partnership deal, not a traditional sales deal.",
        "Requirements": "- Monthly investor update emails\n- Quarterly board meetings\n- Access to key metrics dashboard\n- Referral introductions to portfolio companies",
        "Competition": "N/A — investment deal, not competitive.",
        "Stage History": "- 2026-02-15: → lead (initial conversation with Tom)\n- 2026-02-20: lead → negotiation (term sheet discussions)\n- 2026-02-28: negotiation → closed-won (investment closed)",
        "Notes": "- Tom is actively referring portfolio companies — already introduced Quantum Labs\n- LP meeting in June — prepare a 10-minute update presentation\n- Potential follow-on investment in Series A"
      },
      "company": "coastal-ventures",
      "primary_contact": "tom-nakamura",
      "value": 50000,
      "currency": "USD",
      "stage": "closed-won",
      "probability": 100,
      "expected_close": "2026-02-28",
      "owner": "Our Team",
      "tags": [
        "investment",
        "partner"
      ],
      "created": "2026-02-15",
      "updated": "2026-02-28"
    },
    "meridian-health-platform-migration": {
      "type": "deal",
      "id": "meridian-health-platform-migration",
      "name": "Platform Migration",
      "sections": {
        "Summary": "Meridian Health wants to migrate their patient management system from Oracle Health (on-premise) to our cloud platform. 12 hospitals, 200+ clinics. Phased rollout over 6 months. The deal includes platform licensing ($180K/yr), professional services ($40K), and training ($20K).",
        "Requirements": "- HIPAA-compliant cloud infrastructure (SOC 2 Type II required)\n- Data migration from Oracle Health with zero data loss\n- Phased rollout: 2 pilot hospitals → remaining 10 → clinics\n- 99.99% uptime SLA\n- 24/7 support during migration\n- Integration with their Epic EHR system at 3 facilities\n- Sandbox environment for engineering team evaluation",
        "Competition": "- **Oracle Health** (incumbent) — pushing for contract renewal with discounts\n- **Athenahealth** — in early conversations but haven't done a demo yet\n- Our advantage: modern cloud architecture, better API, lower total cost of ownership",
        "Stage History": "- 2026-03-15: → lead (met Sarah Chen at HealthTech Summit)\n- 2026-03-15: lead → qualified (discovery call confirmed budget and timeline)\n- 2026-03-22: qualified → proposal (sent initial proposal and pricing)\n- 2026-04-01: proposal → negotiation (proposal review meeting, discussing terms)\n- 2026-04-07: pricing accepted (3-year with 10% discount confirmed by Sarah. BAA and sandbox walkthrough remain before contract signing)",
        "Notes": "- Key risk: if Oracle offers deep discounts, Sarah may stay with incumbent — **mitigated: pricing accepted April 7**\n- Marcus Johnson is our champion internally — keep him engaged\n- Need to deliver sandbox environment by April 15 for engineering eval\n- **NEW:** BAA (Business Associate Agreement) required by legal before contract signing — on critical path\n- **NEW:** Sandbox walkthrough scheduled for Thursday April 10 with Marcus's team"
      },
      "company": "meridian-health",
      "primary_contact": "sarah-chen",
      "value": 240000,
      "currency": "USD",
      "stage": "negotiation",
      "probability": 75,
      "expected_close": "2026-05-30",
      "owner": "Our Team",
      "tags": [
        "healthcare",
        "enterprise-sales",
        "migration"
      ],
      "created": "2026-03-15",
      "updated": "2026-04-07"
    },
    "novapay-transaction-analytics": {
      "type": "deal",
      "id": "novapay-transaction-analytics",
      "name": "Transaction Analytics",
      "sections": {
        "Summary": "NovaPay needs real-time transaction analytics for their merchant-facing dashboard. They currently use a homegrown solution that can't scale past 1M events/day. Budget approved for Q2, they want a solution in place by June. Fast-moving deal — similar profile to [[Quantum Labs - API Integration]].",
        "Requirements": "- Real-time event processing (sub-200ms latency)\n- White-labeled merchant analytics dashboard\n- PCI DSS compliance\n- Pricing that scales with transaction volume (usage-based)\n- Integration with their payment processing pipeline",
        "Competition": "- **Build in-house** — their current approach, but it doesn't scale\n- Unknown if they're evaluating other vendors",
        "Stage History": "- 2026-04-07: → lead (intro call via Tom Nakamura referral)",
        "Notes": "- Value TBD — need to understand their event volume to estimate ARR\n- Similar deal profile to Quantum Labs — usage-based API integration\n- If both Quantum Labs and NovaPay close, validates the Coastal Ventures portfolio channel"
      },
      "company": "novapay",
      "primary_contact": "lisa-tran",
      "value": 0,
      "currency": "USD",
      "stage": "lead",
      "probability": 15,
      "expected_close": "2026-06-30",
      "owner": "Our Team",
      "tags": [
        "fintech",
        "analytics",
        "usage-based",
        "coastal-portfolio"
      ],
      "created": "2026-04-07",
      "updated": "2026-04-07"
    },
    "quantum-labs-api-integration": {
      "type": "deal",
      "id": "quantum-labs-api-integration",
      "name": "API Integration",
      "sections": {
        "Summary": "Quantum Labs wants to integrate our analytics API into their code review platform to offer usage insights to their enterprise customers. Usage-based pricing model — estimated $85K ARR based on projected volume. Fast-moving deal with technical founders.",
        "Requirements": "- Sub-100ms API response times (P99)\n- Self-serve onboarding — no manual provisioning\n- Usage-based pricing with volume tiers\n- Comprehensive API documentation and SDKs (Python, JavaScript)\n- Webhook support for real-time event streaming\n- SOC 2 Type II compliance",
        "Competition": "- **Build in-house** — Priya's team could build basic analytics, but it would take 3-4 months\n- **Mixpanel** — too expensive at their scale, not embeddable\n- Our advantage: purpose-built for embedding, usage-based pricing aligns with their model",
        "Stage History": "- 2026-03-12: → lead (intro from Tom Nakamura at Coastal Ventures)\n- 2026-03-18: lead → qualified (technical review confirmed fit)\n- 2026-03-28: qualified → proposal (sent proposal with usage-based pricing tiers)\n- 2026-04-07: proposal → negotiation (contract terms discussed, security review passed)",
        "Notes": "- Priya will make the technical go/no-go decision after security review\n- David Kim handling commercial terms — expects volume discount at scale\n- If this closes, Coastal Ventures portfolio could yield 3-4 more similar deals"
      },
      "company": "quantum-labs",
      "primary_contact": "priya-patel",
      "value": 85000,
      "currency": "USD",
      "stage": "negotiation",
      "probability": 55,
      "expected_close": "2026-06-15",
      "owner": "Our Team",
      "tags": [
        "devtools",
        "api",
        "usage-based"
      ],
      "created": "2026-03-18",
      "updated": "2026-04-07"
    },
    "routeai-logistics-analytics": {
      "type": "deal",
      "id": "routeai-logistics-analytics",
      "name": "Logistics Analytics",
      "sections": {
        "Summary": "RouteAI wants to embed a self-serve analytics dashboard into their route optimization platform. Their 200 delivery company customers need delivery performance metrics — on-time rates, driver efficiency, cost-per-delivery trends. Currently handled by manual SQL queries. Estimated ~$80K ARR based on 15M events/month at standard usage-based tiers.",
        "Requirements": "- Embeddable analytics dashboard (white-labeled, iframe)\n- Real-time data: delivery status, driver location, ETA accuracy\n- Historical trends: on-time %, cost per delivery, volume by region\n- Multi-tenant: each delivery company sees only their own data\n- API access for customers with their own BI tools\n- Usage-based pricing tied to delivery volume (~500K deliveries/day)",
        "Competition": "- **Build in-house** — they have a data team but it's small and focused on route optimization ML\n- Unknown if evaluating other analytics vendors",
        "Stage History": "- 2026-04-07: → lead (demo call with Mike Torres, Coastal Ventures referral)",
        "Notes": "- Third deal from the Coastal Ventures portfolio channel (after Quantum Labs and NovaPay)\n- Mike is the champion but CTO Raj Mehta is the technical gatekeeper\n- Pilot with 3 largest customers planned for May if technical review passes\n- Similar deal profile to Quantum Labs and NovaPay — validates the embedded analytics pattern"
      },
      "company": "routeai",
      "primary_contact": "mike-torres",
      "value": 80000,
      "currency": "USD",
      "stage": "lead",
      "probability": 20,
      "expected_close": "2026-07-31",
      "owner": "Our Team",
      "tags": [
        "logistics",
        "analytics",
        "usage-based",
        "coastal-portfolio"
      ],
      "created": "2026-04-07",
      "updated": "2026-04-07"
    },
    "steelforge-manufacturing-iot-dashboard": {
      "type": "deal",
      "id": "steelforge-manufacturing-iot-dashboard",
      "name": "IoT Dashboard",
      "sections": {
        "Summary": "Steelforge wants a centralized IoT dashboard connecting 500+ pieces of factory floor equipment across 15 plants. Phase 1 is real-time monitoring; Phase 2 is predictive maintenance. Very early stage — they're still building the internal business case. Huge deal if it lands.",
        "Requirements": "- Real-time data ingestion from factory floor sensors (MQTT, OPC-UA)\n- Dashboard for plant managers: equipment health, utilization, alerts\n- Integration with SAP ERP system\n- Single plant pilot before full rollout\n- Predictive maintenance ML models (Phase 2)\n- On-premise edge processing for latency-sensitive data",
        "Competition": "- **Siemens MindSphere** — strong in manufacturing, expensive\n- **PTC ThingWorx** — established IoT platform, complex\n- **AWS IoT** — generic, would require significant custom development\n- Our advantage: faster time to value, better UX, flexible pricing",
        "Stage History": "- 2026-03-20: → lead (met Aisha Mohammed at Industrial IoT World)\n- 2026-04-07: lead → closed-lost (budget not allocated, revisit Q1 2027)",
        "Notes": "- Budget not allocated yet — likely Q1 2027 fiscal year\n- Need to help Aisha build the ROI case for the CIO\n- Start with single plant pilot ($50K) to prove value, then expand\n- Long sales cycle — 6-12 months minimum"
      },
      "company": "steelforge-manufacturing",
      "primary_contact": "aisha-mohammed",
      "value": 320000,
      "currency": "USD",
      "stage": "closed-lost",
      "probability": 0,
      "expected_close": "2027-03-01",
      "owner": "Our Team",
      "tags": [
        "manufacturing",
        "iot",
        "enterprise-sales",
        "long-cycle"
      ],
      "created": "2026-03-25",
      "updated": "2026-04-07"
    }
  },
  "interactions": {
    "2026-03-15-meridian-health-discovery-call": {
      "type": "interaction",
      "id": "2026-03-15-meridian-health-discovery-call",
      "name": "2026-03-15 Meridian Health Discovery Call",
      "sections": {
        "Notes": "45-minute call with Sarah Chen (CTO) and Marcus Johnson (VP Engineering). Sarah outlined their situation: Oracle Health contract expires Q3 2026, they need to migrate 12 hospitals and 200+ clinics to a modern cloud platform. Key requirements:\n\n- HIPAA compliance is non-negotiable\n- Phased rollout — can't risk downtime\n- Need professional services support for migration\n- Budget is approved but final vendor selection by end of April\n\nMarcus asked about our API documentation, SDK support, and whether we've done healthcare migrations before. He wants a sandbox environment to evaluate with his team.\n\nSarah confirmed they're also talking to Athenahealth but haven't done a demo with them yet. She sees us as the frontrunner based on our conference conversation.",
        "Action Items": "- Send sandbox environment credentials to Marcus by March 20\n- Prepare healthcare case study for Sarah\n- Schedule proposal presentation for late March\n- Send technical architecture overview document",
        "Raw Source": "> [!note]- Raw Source\n> Call notes taken during the Zoom meeting on March 15, 2026. Attendees: Sarah Chen, Marcus Johnson (Meridian Health), Our Team."
      },
      "date": "2026-03-15",
      "interaction_type": "call",
      "participants": [
        "sarah-chen",
        "marcus-johnson"
      ],
      "company": "meridian-health",
      "deal": "meridian-health-platform-migration",
      "summary": "Discovery call to understand Meridian's platform migration needs and timeline",
      "tags": [
        "discovery",
        "healthcare"
      ],
      "created": "2026-03-15"
    },
    "2026-03-18-quantum-labs-technical-review": {
      "type": "interaction",
      "id": "2026-03-18-quantum-labs-technical-review",
      "name": "2026-03-18 Quantum Labs Technical Review",
      "sections": {
        "Notes": "60-minute technical review with Priya Patel (CTO) and David Kim (Head of Partnerships). Priya walked through their architecture — they have a React frontend, Go backend, and need to embed our analytics as a white-labeled feature for their enterprise customers.\n\nKey technical requirements confirmed:\n- P99 latency under 100ms — they ran tests on our sandbox and got 85ms, which passes\n- Need webhook support for real-time event streaming to their dashboard\n- Want SDKs in Python and JavaScript (both available)\n- Data residency: need EU region option for GDPR customers\n\nDavid discussed commercial terms:\n- Usage-based pricing preferred — aligns with how they charge their customers\n- Want volume discounts starting at 10M events/month\n- Need a partnership agreement, not just a vendor contract — co-marketing, case study, joint roadmap input\n\nPriya was impressed with our API design. David asked for a formal proposal with pricing tiers.",
        "Action Items": "- Send proposal with usage-based pricing tiers by March 25\n- Provide EU region availability timeline\n- Share security documentation for their compliance review\n- Schedule follow-up to discuss contract terms",
        "Raw Source": "> [!note]- Raw Source\n> Video call on March 18, 2026. Screen sharing of their architecture diagrams and our API documentation."
      },
      "date": "2026-03-18",
      "interaction_type": "meeting",
      "participants": [
        "priya-patel",
        "david-kim"
      ],
      "company": "quantum-labs",
      "deal": "quantum-labs-api-integration",
      "summary": "Technical deep-dive on API capabilities, latency requirements, and integration architecture",
      "tags": [
        "technical-review",
        "api"
      ],
      "created": "2026-03-18"
    },
    "2026-03-22-brightpath-demo-session": {
      "type": "interaction",
      "id": "2026-03-22-brightpath-demo-session",
      "name": "2026-03-22 Brightpath Demo Session",
      "sections": {
        "Notes": "90-minute demo with Elena Rodriguez (Head of Technology) and James O'Brien (IT Director). Walked through the full LMS workflow — course creation, assignment management, grading, and the student/parent portal.\n\nKey moments:\n- Elena loved the teacher dashboard UX — said it was \"miles ahead\" of their current system\n- James asked hard questions about offline mode — showed him the PWA capabilities and local sync. He was satisfied but wants to test in a real low-bandwidth environment\n- SSO demo with Google Workspace went smoothly\n- Data migration: their current system is a custom PostgreSQL app. James will export a sample dataset for us to do a test migration\n- Elena asked about accessibility — confirmed WCAG 2.1 AA compliance\n\nConcerns raised:\n- James worried about the small IT team's capacity to manage the transition\n- Elena needs ROI materials for the board presentation in May\n- Some districts have strict data residency requirements — need on-prem option\n\nOverall positive. Elena said she'll recommend us to the board if the pilot goes well.",
        "Action Items": "- Prepare ROI calculator for Elena's board presentation\n- Set up pilot environment for 5 test districts\n- Send data migration guide to James\n- Provide accessibility audit report",
        "Raw Source": "> [!note]- Raw Source\n> Zoom demo session on March 22, 2026. Screen recording available in shared drive."
      },
      "date": "2026-03-22",
      "interaction_type": "demo",
      "participants": [
        "elena-rodriguez",
        "james-o-brien"
      ],
      "company": "brightpath-education",
      "deal": "brightpath-education-lms-rollout",
      "summary": "Product demo focused on LMS features, offline capabilities, and SSO integration",
      "tags": [
        "demo",
        "education",
        "lms"
      ],
      "created": "2026-03-22"
    },
    "2026-03-25-steelforge-requirements-gathering": {
      "type": "interaction",
      "id": "2026-03-25-steelforge-requirements-gathering",
      "name": "2026-03-25 Steelforge Requirements Gathering",
      "sections": {
        "Notes": "60-minute call with Aisha Mohammed (VP Engineering). She walked through their current state:\n\n- 15 plants across Michigan, Ohio, and Indiana\n- Mix of old and new equipment — oldest machines from the 1990s, newest from 2023\n- Currently using a patchwork of vendor-specific monitoring tools, no centralized view\n- Plant managers make decisions based on experience, not data\n- They lose ~$2M/year in unplanned downtime across all plants\n\nHer vision:\n- Phase 1: Real-time dashboard showing equipment health across all plants\n- Phase 2: Predictive maintenance using ML to forecast failures\n- Phase 3: Integration with SAP for automated work orders\n\nShe wants to start with a single plant pilot at their Detroit facility (50 machines). If successful, roll out to the other 14 plants.\n\nKey constraints:\n- Budget isn't allocated yet — she's building the business case for the CIO\n- IT team is small and focused on SAP — needs a managed solution\n- Factory floor has limited network infrastructure — needs edge computing\n\nNext steps: She'll share equipment inventory and sensor data from the Detroit plant. We'll prepare a pilot proposal with ROI projections.",
        "Action Items": "- Send ROI framework for manufacturing IoT (reduce downtime, improve utilization)\n- Prepare pilot proposal for Detroit plant ($50K estimate)\n- Research MQTT and OPC-UA integration options for their equipment mix\n- Follow up in 2 weeks to check on business case progress",
        "Raw Source": "> [!note]- Raw Source\n> Zoom call on March 25, 2026. Aisha shared photos of factory floor equipment during the call."
      },
      "date": "2026-03-25",
      "interaction_type": "meeting",
      "participants": [
        "aisha-mohammed"
      ],
      "company": "steelforge-manufacturing",
      "deal": "steelforge-manufacturing-iot-dashboard",
      "summary": "Initial requirements gathering for IoT dashboard — factory floor equipment, sensors, and integration needs",
      "tags": [
        "requirements",
        "iot",
        "manufacturing"
      ],
      "created": "2026-03-25"
    },
    "2026-03-28-coastal-ventures-partner-intro": {
      "type": "interaction",
      "id": "2026-03-28-coastal-ventures-partner-intro",
      "name": "2026-03-28 Coastal Ventures Partner Intro",
      "sections": {
        "Notes": "30-minute monthly check-in with Tom Nakamura (Managing Partner).\n\nUpdates shared:\n- Quantum Labs intro is progressing well — they're in proposal stage. Tom pleased.\n- Our MRR is at $28K, up from $20K last month. Tom thinks we need $50K MRR for Series A.\n- Tom offered to intro us to two more portfolio companies: a fintech (NovaPay) and a logistics startup (RouteAI). Both could use our analytics API.\n\nLP meeting discussion:\n- Coastal's annual LP meeting is June 12 in Miami\n- Tom wants us to present for 10 minutes — show product, metrics, vision\n- Good opportunity to meet other Coastal portfolio founders\n\nSeries A timing:\n- Tom recommends targeting Q4 2026 for Series A raise\n- Wants to see 3-4 more enterprise deals closed by then\n- Will make warm intros to Series A funds when we're ready",
        "Action Items": "- Schedule intro calls with NovaPay and RouteAI contacts\n- Prepare LP meeting presentation outline by May 15\n- Send monthly investor update email by April 5\n- Update metrics dashboard with latest MRR numbers",
        "Raw Source": "> [!note]- Raw Source\n> Zoom call on March 28, 2026. Monthly investor check-in."
      },
      "date": "2026-03-28",
      "interaction_type": "meeting",
      "participants": [
        "tom-nakamura"
      ],
      "company": "coastal-ventures",
      "deal": "coastal-ventures-seed-investment",
      "summary": "Monthly check-in with Tom — discussed portfolio intros, Series A timing, and LP meeting prep",
      "tags": [
        "investor",
        "partner",
        "check-in"
      ],
      "created": "2026-03-28"
    },
    "2026-04-01-meridian-health-proposal-review": {
      "type": "interaction",
      "id": "2026-04-01-meridian-health-proposal-review",
      "name": "2026-04-01 Meridian Health Proposal Review",
      "sections": {
        "Notes": "60-minute proposal review with Sarah and Marcus.\n\nPricing discussion:\n- Our proposal: $180K/yr platform + $40K professional services + $20K training = $240K Year 1\n- Sarah said the number is \"in the right range\" but wants a multi-year discount\n- We offered 10% discount for a 3-year commitment — she'll take it to procurement\n\nTechnical discussion (Marcus):\n- Marcus's team tested the sandbox environment — positive feedback on API design\n- Concerns about data migration complexity — wants a dedicated migration engineer from our side\n- Asked for a more detailed migration plan with rollback procedures\n- Wants 99.99% uptime SLA (we proposed 99.9%) — needs to discuss\n\nTimeline:\n- Sarah wants to sign by end of April to start migration before Oracle contract expires in July\n- Pilot with 2 hospitals in May, remaining 10 by September, clinics by December\n\nCompetitors:\n- Athenahealth sent a proposal too — Sarah says it's higher priced but they have more healthcare references\n- Oracle offered a 25% renewal discount — Sarah not interested (\"we need to move forward, not stay stuck\")\n\nOverall very positive. Sarah said we're the preferred vendor, just need to finalize terms.",
        "Action Items": "- Send revised proposal with 3-year pricing option\n- Prepare detailed migration plan with rollback procedures\n- Discuss 99.99% SLA feasibility internally\n- Schedule contract review meeting for week of April 7",
        "Raw Source": "> [!note]- Raw Source\n> Zoom meeting on April 1, 2026. Proposal document shared on screen."
      },
      "date": "2026-04-01",
      "interaction_type": "meeting",
      "participants": [
        "sarah-chen",
        "marcus-johnson"
      ],
      "company": "meridian-health",
      "deal": "meridian-health-platform-migration",
      "summary": "Reviewed proposal and pricing — negotiating terms, timeline, and SLA commitments",
      "tags": [
        "negotiation",
        "proposal-review"
      ],
      "created": "2026-04-01"
    },
    "2026-04-03-quantum-labs-contract-discussion": {
      "type": "interaction",
      "id": "2026-04-03-quantum-labs-contract-discussion",
      "name": "2026-04-03 Quantum Labs Contract Discussion",
      "sections": {
        "Notes": "45-minute call focused on commercial terms. David Kim led, Priya joined for technical clarifications.\n\nPricing agreement:\n- Tier 1: 0-5M events/month — $0.001/event\n- Tier 2: 5-20M events/month — $0.0008/event\n- Tier 3: 20M+ events/month — $0.0006/event\n- Minimum commitment: $5K/month ($60K/yr), estimated $85K based on their projected volume\n- David happy with usage-based model, wants quarterly true-up billing\n\nSLA discussion:\n- P99 latency: 100ms (agreed)\n- Uptime: 99.95% (agreed)\n- Support: business hours with 4-hour response for P1 issues\n- David wants financial credits for SLA breaches — standard 10% of monthly bill per breach\n\nPartnership terms:\n- Co-marketing: joint case study and blog post within 90 days of launch\n- Joint roadmap input: quarterly meeting to discuss feature requests\n- Priya wants early access to beta features\n\nSecurity review:\n- Priya confirmed our SOC 2 Type II report is satisfactory\n- Remaining item: pen test results from last quarter — we need to send those\n- EU region: available Q3 2026 — acceptable for their timeline\n\nNext step: David will prepare redlines on our standard agreement. Targeting signature by end of April.",
        "Action Items": "- Send penetration test results to Priya\n- Prepare partnership agreement draft with co-marketing terms\n- Send standard contract for David's review\n- Confirm EU region launch timeline with engineering",
        "Raw Source": "> [!note]- Raw Source\n> Zoom call on April 3, 2026."
      },
      "date": "2026-04-03",
      "interaction_type": "call",
      "participants": [
        "david-kim",
        "priya-patel"
      ],
      "company": "quantum-labs",
      "deal": "quantum-labs-api-integration",
      "summary": "Contract terms discussion — pricing tiers, SLAs, and partnership agreement structure",
      "tags": [
        "contract",
        "negotiation",
        "pricing"
      ],
      "created": "2026-04-03"
    },
    "2026-04-05-brightpath-stakeholder-alignment": {
      "type": "interaction",
      "id": "2026-04-05-brightpath-stakeholder-alignment",
      "name": "2026-04-05 Brightpath Stakeholder Alignment",
      "sections": {
        "Notes": "45-minute call with Elena and James to align on next steps before the May board meeting.\n\nPilot plan:\n- 5 districts selected for pilot — mix of urban and rural\n- Elena wants pilot running by May 1 so she can show results at the May 15 board meeting\n- James will coordinate with district IT contacts for SSO setup\n- We'll provide dedicated onboarding support for the pilot\n\nBoard presentation:\n- Elena needs a one-page ROI summary by April 20\n- Key metrics to highlight: cost savings vs. current system, teacher satisfaction data from similar deployments, time savings on admin tasks\n- Elena will present; she wants us available for Q&A via phone if needed\n\nTechnical update (James):\n- James exported a sample dataset from their current system — 50K student records, 500 courses\n- Test migration went well but found 3 data format issues we need to address\n- SSO with Google Workspace working, Microsoft 365 needs configuration adjustments\n- James confirmed he's comfortable recommending us to the board if pilot data looks good\n\nRisk:\n- If pilot doesn't show clear results by May 10, Elena may delay the board ask to August\n- Canvas offered a free 6-month pilot — competitive pressure",
        "Action Items": "- Set up pilot environment for 5 districts by April 15\n- Fix 3 data migration format issues James identified\n- Prepare one-page ROI summary for board presentation\n- Resolve Microsoft 365 SSO configuration issue",
        "Raw Source": "> [!note]- Raw Source\n> Zoom call on April 5, 2026."
      },
      "date": "2026-04-05",
      "interaction_type": "call",
      "participants": [
        "elena-rodriguez",
        "james-o-brien"
      ],
      "company": "brightpath-education",
      "deal": "brightpath-education-lms-rollout",
      "summary": "Discussed pilot plan, board presentation strategy, and technical concerns about data migration",
      "tags": [
        "stakeholder-alignment",
        "pilot-planning"
      ],
      "created": "2026-04-05"
    },
    "2026-04-07-meridian-health-pricing-approval-email": {
      "type": "interaction",
      "id": "2026-04-07-meridian-health-pricing-approval-email",
      "name": "2026-04-07 Meridian Health Pricing Approval Email",
      "sections": {
        "Notes": "Inbound email from [[Sarah Chen]]. Three key updates:\n\n1. **Pricing accepted.** The 3-year option with 10% discount works for them. This is a major milestone — removes the biggest commercial blocker.\n2. **Sandbox walkthrough Thursday.** [[Marcus Johnson]] wants to schedule a walkthrough for his engineering team this Thursday (April 10). Need to confirm our availability.\n3. **BAA required.** Their legal team needs a Business Associate Agreement (HIPAA requirement) signed before they can proceed with the contract. This is a new requirement — wasn't mentioned in prior discussions.",
        "Action Items": "- Confirm availability for Thursday sandbox walkthrough with Marcus's team\n- Prepare and send BAA (Business Associate Agreement) to Meridian legal\n- Update internal deal tracking — pricing is no longer a blocker",
        "Raw Source": "> [!note]- Raw Source\n> From: Sarah Chen <s.chen@meridianhealth.com>\n> Date: April 7, 2026\n> Subject: Re: Revised Proposal\n>\n> Hi team, we reviewed the 3-year pricing option internally. The 10% discount works for us. Marcus wants to schedule the sandbox walkthrough for his team this Thursday. Can you confirm availability? Also, our legal team will need a BAA (Business Associate Agreement) signed before we can proceed. — Sarah"
      },
      "date": "2026-04-07",
      "interaction_type": "email",
      "participants": [
        "sarah-chen"
      ],
      "company": "meridian-health",
      "deal": "meridian-health-platform-migration",
      "summary": "Sarah confirmed 3-year pricing with 10% discount works. Marcus wants sandbox walkthrough Thursday. BAA required before signing.",
      "tags": [
        "pricing-approved",
        "contract",
        "milestone"
      ],
      "created": "2026-04-07"
    },
    "2026-04-07-novapay-intro-call": {
      "type": "interaction",
      "id": "2026-04-07-novapay-intro-call",
      "name": "2026-04-07 NovaPay Intro Call",
      "sections": {
        "Notes": "30-minute intro call with Lisa Tran (CTO, NovaPay). [[Tom Nakamura]] from [[Coastal Ventures]] made the introduction.\n\nNovaPay builds payment infrastructure for e-commerce platforms. Series A ($12M raised), 30 employees, based in New York. They serve ~500 merchants.\n\nTheir need: real-time transaction analytics for their merchant dashboard. Current homegrown solution can't scale past 1M events/day. Requirements:\n- Real-time event processing (sub-200ms)\n- Merchant-facing analytics dashboard (white-labeled)\n- PCI DSS compliance\n- Pricing that scales with transaction volume\n\nLisa said budget is approved for Q2. She wants to see a demo next week and fast-track evaluation — solution needed by June.",
        "Action Items": "- Schedule demo for next week (Lisa prefers Tuesday or Wednesday)\n- Send PCI DSS compliance documentation\n- Prepare fintech-specific pricing proposal\n- Let [[Tom Nakamura]] know the intro went well",
        "Raw Source": "> [!note]- Raw Source\n> # Meeting Notes — April 7, 2026\n>\n> **Meeting:** Follow-up call with NovaPay (intro from Tom Nakamura)\n> **Attendees:** Lisa Tran (CTO, NovaPay), Our Team\n> **Duration:** 30 minutes\n>\n> Lisa Tran is the CTO of NovaPay, a fintech startup building payment infrastructure for e-commerce platforms. They're a Coastal Ventures portfolio company — Tom Nakamura made the introduction.\n>\n> NovaPay needs real-time transaction analytics for their merchant dashboard. Currently they're using a homegrown solution that can't scale past 1M events/day. They need:\n> - Real-time event processing (sub-200ms)\n> - Merchant-facing analytics dashboard (white-labeled)\n> - PCI DSS compliance\n> - Pricing that scales with transaction volume\n>\n> Lisa said they have budget approved for Q2. She wants to see a demo next week and fast-track evaluation — they need a solution in place by June.\n>\n> NovaPay is Series A ($12M raised), 30 employees, based in New York. They serve ~500 e-commerce merchants.\n>\n> ## Action Items\n> - Schedule demo for next week (Lisa prefers Tuesday or Wednesday)\n> - Send PCI DSS compliance documentation\n> - Prepare fintech-specific pricing proposal\n> - Let Tom know the intro went well"
      },
      "date": "2026-04-07",
      "interaction_type": "call",
      "participants": [
        "lisa-tran"
      ],
      "company": "novapay",
      "deal": "novapay-transaction-analytics",
      "summary": "Intro call with Lisa Tran (CTO) — discussed analytics needs, timeline, and next steps",
      "tags": [
        "discovery",
        "fintech",
        "coastal-referral"
      ],
      "created": "2026-04-07"
    },
    "2026-04-07-routeai-demo-call": {
      "type": "interaction",
      "id": "2026-04-07-routeai-demo-call",
      "name": "2026-04-07 RouteAI Demo Call",
      "sections": {
        "Notes": "40-minute demo call with Mike Torres (VP Product, RouteAI). [[Tom Nakamura]] from [[Coastal Ventures]] made the introduction.\n\nRouteAI builds route optimization software for last-mile delivery companies. Series A ($8M raised), 25 employees, Chicago. ~200 customers processing 500K deliveries/day.\n\nTheir customers are asking for analytics — on-time rates, driver efficiency, cost-per-delivery trends. Currently handled by manual SQL queries by their data team. They want to embed a self-serve dashboard.\n\nRequirements confirmed:\n- Embeddable white-labeled dashboard (iframe)\n- Real-time: delivery status, driver location, ETA accuracy\n- Historical: on-time %, cost per delivery, volume by region\n- Multi-tenant: each delivery company sees only their data\n- API access for BI tool integration\n\nMike was impressed with our demo — especially real-time streaming and white-label customization. Said it's \"exactly what our customers have been asking for.\"\n\nPricing: usage-based tied to deliveries. 500K/day = ~15M events/month. Ballpark $70-90K ARR.\n\nNext steps: Mike needs CTO [[Raj Mehta]] to approve the technical architecture. Technical review next week. Pilot with 3 customers in May if approved.",
        "Action Items": "- Schedule technical review with [[Raj Mehta]] for next week\n- Send multi-tenant architecture documentation\n- Prepare pilot proposal for 3 customer accounts\n- Send pricing proposal with usage-based tiers\n- Update [[Tom Nakamura]] on the call",
        "Raw Source": "> [!note]- Raw Source\n> # Meeting Notes — April 7, 2026\n>\n> **Meeting:** Demo call with RouteAI (intro from Tom Nakamura)\n> **Attendees:** Mike Torres (VP Product, RouteAI), Our Team\n> **Duration:** 40 minutes\n>\n> Mike Torres is VP Product at RouteAI, a logistics startup building route optimization software for last-mile delivery companies. They're a Coastal Ventures portfolio company — Tom Nakamura made the introduction during our March check-in.\n>\n> RouteAI has a solid route optimization engine but their customers keep asking for delivery performance analytics — on-time rates, driver efficiency, cost-per-delivery trends. They've been manually pulling reports from their database and want to embed a self-serve analytics dashboard into their platform.\n>\n> Key requirements: embeddable dashboard, real-time data, historical trends, multi-tenant, API access. Series A ($8M raised), 25 employees, Chicago. ~200 customers, 500K deliveries/day.\n>\n> Mike impressed with demo. Needs CTO (Raj Mehta) buy-in. Pilot with 3 customers in May. Estimated $70-90K ARR."
      },
      "date": "2026-04-07",
      "interaction_type": "demo",
      "participants": [
        "mike-torres"
      ],
      "company": "routeai",
      "deal": "routeai-logistics-analytics",
      "summary": "Product demo for logistics analytics dashboard — Mike impressed, needs CTO buy-in next",
      "tags": [
        "demo",
        "logistics",
        "coastal-referral"
      ],
      "created": "2026-04-07"
    }
  },
  "tasks": {
    "confirm-thursday-sandbox-walkthrough": {
      "type": "task",
      "id": "confirm-thursday-sandbox-walkthrough",
      "name": "Confirm Thursday sandbox walkthrough",
      "sections": {
        "Details": "[[Marcus Johnson]] wants to schedule a sandbox walkthrough for his engineering team this Thursday (April 10). Confirm our availability and send calendar invite. Make sure the sandbox environment is up to date with latest features."
      },
      "title": "Confirm Thursday sandbox walkthrough",
      "assigned_to": "Our Team",
      "related_to": [
        "Meridian Health - Platform Migration",
        "Marcus Johnson"
      ],
      "due_date": "2026-04-08",
      "priority": "high",
      "status": "todo",
      "created": "2026-04-07"
    },
    "follow-up-with-steelforge-on-budget": {
      "type": "task",
      "id": "follow-up-with-steelforge-on-budget",
      "name": "Follow up with Steelforge on budget",
      "sections": {
        "Details": "Check in with Aisha Mohammed on her progress building the internal business case for the CIO. Send the ROI framework for manufacturing IoT (reduced downtime, improved utilization metrics). Prepare pilot proposal for Detroit plant (~$50K).\n\nThis is a long-cycle deal — don't push too hard, just stay warm and helpful."
      },
      "title": "Follow up with Steelforge on budget",
      "assigned_to": "Our Team",
      "related_to": [
        "Steelforge Manufacturing - IoT Dashboard",
        "Aisha Mohammed"
      ],
      "due_date": "2026-04-09",
      "priority": "low",
      "status": "todo",
      "created": "2026-03-25"
    },
    "prepare-brightpath-pilot-timeline": {
      "type": "task",
      "id": "prepare-brightpath-pilot-timeline",
      "name": "Prepare Brightpath pilot timeline",
      "sections": {
        "Details": "Set up pilot environment for 5 districts by April 15. Fix the 3 data migration format issues James identified. Prepare one-page ROI summary for Elena's board presentation (due April 20). Resolve Microsoft 365 SSO configuration issue.\n\nElena needs the pilot running by May 1 to show results at the May 15 board meeting."
      },
      "title": "Prepare Brightpath pilot timeline",
      "assigned_to": "Our Team",
      "related_to": [
        "Brightpath Education - LMS Rollout",
        "Elena Rodriguez"
      ],
      "due_date": "2026-04-15",
      "priority": "medium",
      "status": "todo",
      "created": "2026-04-05"
    },
    "schedule-novapay-demo": {
      "type": "task",
      "id": "schedule-novapay-demo",
      "name": "Schedule NovaPay demo",
      "sections": {
        "Details": "Schedule product demo with Lisa Tran for next week (she prefers Tuesday April 8 or Wednesday April 9). Also send PCI DSS compliance documentation ahead of the demo. Prepare fintech-specific pricing proposal with usage-based tiers."
      },
      "title": "Schedule NovaPay demo",
      "assigned_to": "Our Team",
      "related_to": [
        "NovaPay - Transaction Analytics",
        "Lisa Tran"
      ],
      "due_date": "2026-04-09",
      "priority": "high",
      "status": "todo",
      "created": "2026-04-07"
    },
    "schedule-quantum-labs-security-review": {
      "type": "task",
      "id": "schedule-quantum-labs-security-review",
      "name": "Schedule Quantum Labs security review",
      "sections": {
        "Details": "Send penetration test results from last quarter to Priya Patel. She needs these to complete her security review before signing. Also send the standard contract to David Kim for redlines. Targeting contract signature by end of April."
      },
      "title": "Schedule Quantum Labs security review",
      "assigned_to": "Our Team",
      "related_to": [
        "Quantum Labs - API Integration",
        "Priya Patel"
      ],
      "due_date": "2026-04-12",
      "priority": "high",
      "status": "todo",
      "created": "2026-04-03"
    },
    "schedule-routeai-technical-review": {
      "type": "task",
      "id": "schedule-routeai-technical-review",
      "name": "Schedule RouteAI technical review",
      "sections": {
        "Details": "Get [[Raj Mehta]]'s contact details from [[Mike Torres]] and schedule a technical review call for next week. Send multi-tenant architecture documentation ahead of the call. Also prepare the pilot proposal for 3 customer accounts and a pricing proposal with usage-based tiers."
      },
      "title": "Schedule RouteAI technical review",
      "assigned_to": "Our Team",
      "related_to": [
        "RouteAI - Logistics Analytics",
        "Raj Mehta"
      ],
      "due_date": "2026-04-10",
      "priority": "high",
      "status": "todo",
      "created": "2026-04-07"
    },
    "send-baa-to-meridian-legal": {
      "type": "task",
      "id": "send-baa-to-meridian-legal",
      "name": "Send BAA to Meridian legal",
      "sections": {
        "Details": "Meridian Health's legal team requires a signed Business Associate Agreement (BAA) before the contract can proceed. This is a HIPAA compliance requirement. Check if we have a standard BAA template — if not, get legal to prepare one. This is on the critical path to closing."
      },
      "title": "Send BAA to Meridian legal",
      "assigned_to": "Our Team",
      "related_to": [
        "Meridian Health - Platform Migration",
        "Sarah Chen"
      ],
      "due_date": "2026-04-10",
      "priority": "high",
      "status": "todo",
      "created": "2026-04-07"
    },
    "send-meridian-revised-proposal": {
      "type": "task",
      "id": "send-meridian-revised-proposal",
      "name": "Send Meridian revised proposal",
      "sections": {
        "Details": "Prepare and send revised proposal with 3-year pricing option (10% discount for 3-year commitment). Include detailed migration plan with rollback procedures. Address the 99.99% uptime SLA request — check feasibility internally before committing.\n\nSarah wants to sign by end of April. This is the highest priority task."
      },
      "title": "Send Meridian revised proposal",
      "assigned_to": "Our Team",
      "related_to": [
        "Meridian Health - Platform Migration",
        "Sarah Chen"
      ],
      "due_date": "2026-04-10",
      "priority": "high",
      "status": "done",
      "created": "2026-04-01"
    },
    "update-tom-on-novapay-intro": {
      "type": "task",
      "id": "update-tom-on-novapay-intro",
      "name": "Update Tom on NovaPay intro",
      "sections": {
        "Details": "Let [[Tom Nakamura]] know the NovaPay intro went well. Lisa is interested and wants a demo next week. Good to keep Tom in the loop since he made the referral."
      },
      "title": "Update Tom on NovaPay intro",
      "assigned_to": "Our Team",
      "related_to": [
        "Tom Nakamura",
        "NovaPay"
      ],
      "due_date": "2026-04-08",
      "priority": "low",
      "status": "todo",
      "created": "2026-04-07"
    }
  }
};
